aspect_keywords = {
    "food": [
        "food",
        "dish",
        "taste",
        "flavor",
        "menu",
        "portion",
        "appetizer",
        "entree",
        "dessert",
        "cuisine",
    ],
    "service": [
        "service",
        "waiter",
        "waitress",
        "server",
        "staff",
        "attentive",
        "friendly",
        "rude",
        "slow",
        "quick",
    ],
    "ambiance": [
        "ambiance",
        "atmosphere",
        "decor",
        "lighting",
        "music",
        "noise",
        "crowded",
        "quiet",
        "romantic",
        "casual",
    ],
    "price": [
        "price",
        "expensive",
        "cheap",
        "affordable",
        "value",
        "worth",
        "cost",
        "bill",
        "payment",
        "budget",
    ],
    "cleanliness": [
        "clean",
        "dirty",
        "hygiene",
        "sanitary",
        "spotless",
        "filthy",
        "messy",
        "neat",
        "tidy",
        "organized",
    ],
    "location": [
        "location",
        "parking",
        "accessible",
        "convenient",
        "downtown",
        "area",
        "neighborhood",
        "street",
        "corner",
        "block",
        "place",
    ],
    "wait_time": [
        "wait",
        "line",
        "queue",
        "busy",
        "reservation",
        "seating",
        "rush",
        "quick",
        "slow",
        "prompt",
    ],
    "portion": [
        "portion",
        "size",
        "quantity",
        "amount",
        "serving",
        "generous",
        "small",
        "large",
        "huge",
        "tiny",
    ],
    "parking": [
        "parking",
        "lot",
        "garage",
        "valet",
        "spot",
        "street",
        "meter",
        "free",
        "difficult",
        "easy",
    ],
    "delivery": [
        "delivery",
        "takeout",
        "pickup",
        "order",
        "online",
        "driver",
        "time",
        "late",
        "fast",
        "packaging",
    ],
    "overall": [
        "overall",
        "experience",
        "recommend",
        "disappoint",
        "satisfactory",
    ],
    "atmosphere": [
        "ambiance",
        "decor",
        "lighting",
        "music",
    ],
}
